# Generated by Django 3.0.6 on 2020-06-23 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multyPY', '0002_auto_20200623_2054'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exam',
            options={'permissions': (('canExamBase_number1', 'Can Take Exam for The table of 1'), ('canExamBase_number2', 'Can Take Exam for The table of 2'), ('canExamBase_number3', 'Can Take Exam for The table of 3'), ('canExamBase_number4', 'Can Take Exam for The table of 4'), ('canExamBase_number5', 'Can Take Exam for The table of 5'), ('canExamBase_number6', 'Can Take Exam for The table of 6'), ('canExamBase_number7', 'Can Take Exam for The table of 7'), ('canExamBase_number8', 'Can Take Exam for The table of 8'), ('canExamBase_number9', 'Can Take Exam for The table of 9'), ('canExamBase_number10', 'Can Take Exam for The table of 10'))},
        ),
    ]
