# Generated by Django 3.0.6 on 2020-06-23 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multyPY', '0004_auto_20200623_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='examanswer',
            name='correct',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
