# Generated by Django 3.0.6 on 2020-06-24 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multyPY', '0005_examanswer_correct'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=16)),
            ],
        ),
    ]
