# Generated by Django 3.0.6 on 2020-06-24 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multyPY', '0006_studentkey_teacherkey'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalexamanswer',
            name='correct',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
