# Generated by Django 5.2.5 on 2025-08-26 19:04

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("multyPY", "0007_finalexamanswer_correct"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="time_taken",
            field=models.PositiveIntegerField(
                blank=True, help_text="Time taken to answer in seconds", null=True
            ),
        ),
        migrations.AddField(
            model_name="exam",
            name="passed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="exam",
            name="time_taken",
            field=models.PositiveIntegerField(
                blank=True, help_text="Total time taken for exam in seconds", null=True
            ),
        ),
        migrations.AddField(
            model_name="examanswer",
            name="time_taken",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Time taken for this specific answer in seconds",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="finalexam",
            name="date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="finalexam",
            name="passed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="finalexam",
            name="time_taken",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Total time taken for final exam in seconds",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="finalexam",
            name="total_correct",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AddField(
            model_name="finalexamtable",
            name="number_of_correct",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(10),
                ],
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="question",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="studentkey",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="studentkey",
            name="used_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="studentkey",
            name="used_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="teacherkey",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="teacherkey",
            name="used_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="teacherkey",
            name="used_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="answer",
            name="answer",
            field=models.IntegerField(
                help_text="Student's answer to the question",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(1000),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="answer",
            name="correct",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="answer",
            name="date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="exam",
            name="base_number",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(12),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="exam",
            name="date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="exam",
            name="number_of_correct",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(10),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="examanswer",
            name="answer",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(1000),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="examanswer",
            name="correct",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="examanswer",
            name="multiplier",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(12),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="finalexamanswer",
            name="answer",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(1000),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="finalexamanswer",
            name="correct",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="finalexamanswer",
            name="multiplier",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(12),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="finalexamtable",
            name="base_number",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(12),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="base_number",
            field=models.IntegerField(
                help_text="Multiplication table base (1-12)",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(12),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="multiplier",
            field=models.IntegerField(
                help_text="Multiplier value (1-12)",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(12),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="options",
            field=models.TextField(
                help_text="JSON array of answer options",
                validators=[django.core.validators.int_list_validator],
            ),
        ),
        migrations.AlterField(
            model_name="studentkey",
            name="key",
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name="teacherkey",
            name="key",
            field=models.CharField(max_length=16, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name="examanswer",
            unique_together={("exam", "multiplier")},
        ),
        migrations.AlterUniqueTogether(
            name="finalexamanswer",
            unique_together={("finalExamTablexamTable", "multiplier")},
        ),
        migrations.AlterUniqueTogether(
            name="finalexamtable",
            unique_together={("examTable", "base_number")},
        ),
        migrations.AddIndex(
            model_name="answer",
            index=models.Index(
                fields=["user", "date"], name="multyPY_ans_user_id_04a204_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="answer",
            index=models.Index(
                fields=["question", "correct"], name="multyPY_ans_questio_1a2ce1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="exam",
            index=models.Index(
                fields=["user", "date"], name="multyPY_exa_user_id_36ed88_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="exam",
            index=models.Index(
                fields=["base_number", "number_of_correct"],
                name="multyPY_exa_base_nu_aec894_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="examanswer",
            index=models.Index(
                fields=["exam", "correct"], name="multyPY_exa_exam_id_9ea09d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="finalexam",
            index=models.Index(
                fields=["user", "date"], name="multyPY_fin_user_id_72091f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(
                fields=["base_number", "multiplier"],
                name="multyPY_que_base_nu_44daa7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(
                fields=["created_at"], name="multyPY_que_created_1aeeee_idx"
            ),
        ),
    ]
